# Generated by Django 3.0.6 on 2021-03-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainnotes.Notes'),
        ),
    ]
